config/routes.rb
EVerification::Application.routes.draw do
  [404,500].each do |page|
    get page, :to => "errors#show", code: page
  end

  # unless Rails.application.config.consider_all_requests_local
  #   match '*not_found', to: 'errors#error_404'
  # end

  root :to => 'dashboards#index'
  get "help_topics/" => 'help_topics#index', :as => :help_topics

  get "help_topics/how-to-make-applicant" => 'help_topics#make_customer', :as => :make_customer
  get "help_topics/how-to-make-co-applicant" => 'help_topics#make_co_applicant', :as => :make_co_applicant
  get 'pending_customers' => "reports#pending", :as => :pending_customers
  get 'completed_customers' => "reports#completed", :as => :completed_customers
  get 'progress_customers' => "reports#progress", :as => :progress_customers
	get 'get_branch_code' => "branches#get_branch_code"
	get 'get_area_name' => "branches#get_area_name"
	get 'get_area' => "branches#get_area"
  resources :branches
  resources :reports do
   get :generated_report
   get :generate_report
  end
  resources :co_applicant_serveys
  get "customers/download_ready_customers"
  get "customers/download_ready_co_applicants"
  get "customers/download_ready_customers_business"
  get "customers/download_ready_co_applicants_business"

  get "customers/completed_customers_today"
  get "customers/in_progress_today"
  get "customers/old_pending_customers"
  get "customers/daily_customers"
  get "customers/assigned_data_today"
  get "customers/daily_pending_customers"
  get "customers/daily_completed_customers"
  get "customers/daily_progress_customers"
  get "reports/show"
  get 'customers/reset'
  get "co_applicant_businesses/index"
  get "reports/to_excel" => "reports#to_excel", :as => :excel
  get "customers/search_results" => "customers#customer_search", :as => :search
  get "dashboards/index"
  get "headshot_demo/index"
  get "customers/cust_residential"
  get "customers/cust_business"
  get "customers/cust_pending"
  get "customers/cust_in_progress"
  get "customers/cust_ready"
  get "customers/cust_completed"
  get "customers/customer_search_results" => "customers#search", :as => :customer_search
  post "headshot/capture" => 'headshot#capture', :as => :headshot_capture

  #resources :searches
  resources :work_serveys
  resources :webcam_pictures
  resources :customers
  resources :tabs do
   get :tab_status
  end
  resources :profiles
  resources :pincodes
  resources :customer_documents

  resources :co_applicant_businesses do
   member do
     post :business_verification
     get :business_verification
     post :accept
     get :accept
     get :print_co_applicant_business
     post :re_indicated
     get :re_indicated
   end
     collection do
       post :assign_all
     end
  end

  resources :co_applicants do
    member do
     post :co_applicant_verification
     get :co_applicant_verification
     post :accept
     get :accept
     get :print_co_applicant
     post :re_indicated
     get :re_indicated
    end
     collection do
       post :assign_all
     end
  end
  resources :co_applicant_work_details
  resources :customer_verifications
  resources :business_verifications
  resources :co_applicant_verifications
  resources :client_verifications
  resources :serveys

  resources :customers do
    member do
     post :customer_verification
     get :customer_verification
     get :print_customer
     post :customer_work_servey_verification
     get :customer_work_servey_verification
     post :accept
     get :accept
     post :re_indicated
     get :re_indicated
    end
     collection do
       post :assign_all
     end
  end
  resources :businesses do
   member do
     post :business_verification
     get :business_verification
     post :accept
     get :print_business_form
     get :accept
     post :re_indicated
     get :re_indicated
   end
     collection do
       post :assign_all
     end
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :registrations => "registrations" } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

end

app/controllers/businesses_controller.rb
class BusinessesController < InheritedResources::Base
   before_filter :authenticate_user!
   layout 'print_layout', :only => :print_business_form
   load_and_authorize_resource

 def index
   @business = Business.all
    respond_to do |format|
      format.html # index.html.erb
			format.xlsx {
										 send_data Business.to_xlsx.to_stream.read,
										 :filename => 'Customers.xlsx',
										 :type => "application/vnd.openxmlformates-officedocument.spreadsheetml.sheet"
            			}
    end

 end

 def create
  @business = Business.create(params[:business])

   if @business.save
    redirect_to @business.customer, :notice => "Details Added."
   else
    redirect_to @business.customer, :alert => "you must have kept few empty fields or Something went wrong , please contact the administrator!."
 end
 end

 def show
  @business = Business.find(params[:id])
  @business_verification = BusinessVerification.new
 end

 def business_verification
   @business = Business.find(params[:business_id])
   @tab = Tab.find(:all)
   @verification = BusinessVerification.create(params[:business_verification])
    @verification.user_id = current_user.id
    @verification.business_id = @business.id

     if @verification.save
        @verification.business.submit!
        @user = User.find_by_role('super_user')
        #VerificationMailer.verification_confirmation(@user).deliver
        redirect_to @business, :notice =>"record has been send for verification"
    end
  end

 def assign_all
    params[:business_verification][:business_ids].each do |t|
     params_business = {}
     params_business['business_id'] = t
     @t = BusinessVerification.create(params_business)
     @t.tab_id = params[:tab_id].to_i
     if @t.save
        @t.business.submit!
     end
    end
     redirect_to customers_cust_ready_path, notice: "successful."
 end

  def accept
    @business = Business.find(params[:business_id])
    @business.accept!

    respond_to do |format|
       if @business.update_attributes(params[:business])
         format.html { redirect_to root_url, notice: 'Status was successfully updated.' }
         format.json { head :ok }
       else
         format.html { render action: "edit" }
         format.json { render json: @business.errors, status: :unprocessable_entity }
       end
     end
  end

  def edit
   @customer = Customer.find(params[:customer_id])
   @business = Business.find(params[:id])
   @application_ref_no = @customer.application_ref_no
  end


  def re_indicated
    @business = Business.find(params[:business_id])
    @business.re_indicated!

    respond_to do |format|
       if @business.update_attributes(params[:business])
         format.html { redirect_to root_url, notice: 'Status was successfully updated.' }
         format.json { head :ok }
       else
         format.html { render action: "edit" }
         format.json { render json: @business.errors, status: :unprocessable_entity }
       end
     end
  end

  def destroy
    @business = Business.find(params[:id])
    @business.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end

  def print_business_form
    @print_form = Business.find(params[:business_id])
  end


end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<div id="business" style ="padding-left:40px">
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="row">
  <strong class="label label-info">
    <%= @customer.client.name %> | <%= @customer.branch.name %> | <%= @customer.branch_code %> | <%= @application_ref_no %> | <%= @application_ref_no %> | <%= @customer.applicant_name %>
</strong> <br>

  <div class="field_name">
   <%= f.check_box :document_required %>
   <i style ="padding-left:20px;color:green">Check this if photocopy of the customers document is required. else leave it as it is</i>
  </div>
    <%= f.hidden_field :customer_id, :value=> "#{@customer.id}" %>
    <%= f.hidden_field :application_status, :value=> "BUSINESS" %>
    <%= f.hidden_field :agency_name, :value=>"Scorp Enterprises" %>
    <%= f.hidden_field :application_ref_no, :value=> "#{@application_ref_no}" %>
    <%= f.hidden_field :fh_code, :value=> "#{@application_ref_no}" %>
    <%= f.hidden_field :applicant_name, :value=> "#{@customer.applicant_name}" %>
    <%= f.hidden_field :client_id, :value=> "#{@customer.client_id}" %>
    <%= f.hidden_field :branch_id, :value=> "#{@customer.branch_id}" %>
    <%= f.hidden_field :branch_code, :value=> "#{@customer.branch_code}" %>
  <br><br>

  <div class="row">
  <div class="field_name">
    <%= f.label :'Name OF The Company' %>
    <%= f.text_field :company_name %>
  </div>

  <div class="field_name">
    <%= f.label :landmark %>
    <%= f.text_field :landmark %>
  </div>
  </div>

  <div class="field_name">
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>

  <div class="field_name">
    <%= f.label :country_name %>
    <%= f.text_field :country_name, :value => "INDIA" %>
  </div>
  <div class="field_name">
    <%= f.label :country_state %>
    <%= f.text_field :country_state, :value => "Maharashtra" %>
  </div>

<script stype="javascript">
 function getArea(obj){
 $.ajax({url:'/get_area',
 dataType: 'script',
 type: 'get',
 data: {id: obj.value},
 success: function(data){
 }
 });}
</script>

  <div class="field_name">
    <%= f.label :Select_city %>
    <%= f.collection_select :city_id, City.all, :id, :name, {}, {:class => 'text_field', :onchange => 'getArea(this)'} %>
  </div>

<script stype="javascript">
 function getAreaname(obj){
 $.ajax({url:'/get_area_name',
 dataType: 'text',
 type: 'get',
 data: {id: obj.value},
 success: function(data){
  $("#business_area_name").val(data);
 }
 });}
</script>

  <div class="field_name">
    <%= f.label :Area_Name %>
    <div id ="area_name"><%= f.collection_select :pincode_id, Pincode.all, :id, :name, {:prompt => true} ,{:class => 'text_field', :onchange => 'getAreaname(this)'} %></div>
  </div>

  <div class="field_name">
    <%= f.label :'Selected pincode', :class => 'control-label' %>
    <%= f.text_field :area_name, :class => 'text_field' %>
  </div>


</div>
  <div class="actions">
    <%= f.submit 'Save coapplicant', :class => 'btn btn-primary btn-small' %>
  </div>
<% end %>
</div>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<%- model_class = Business -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %>
<b><%= link_to "View Customers",
            customers_path,
            :class=>"btn btn-primary btn-small", :style=>"margin-right:150px;float:right" %></b>
<!--<b><%= link_to "Add New Business",
            new_business_path,
            :class=>"btn btn-primary btn-small", :style=>"margin-right:150px;float:right" %></b><br><br></h1>-->
</div>


<table class="table table-striped">
  <tr>
    <th>Application ref no</th>
    <th>Agency name</th>
    <th>Fh code</th>
    <th>Applicant name</th>
    <th>Status</th>
    <th>verifier</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @businesses.each do |customer| %>

  <tr>
    <td><%= link_to "scorpeo/ #{Date.today}/ #{customer.application_ref_no}", customer %></td>
    <td><%= customer.agency_name %></td>
    <td><%= "scorpeo/ #{Date.today}/ #{customer.application_ref_no} #{customer.fh_code}" %></td>
    <td><%= customer.customer.applicant_name %></td>

<% if customer.status=='submitted' %>
     <td><span class="label label-info"> Submitted </span></td>  
    <% end %>
<% if customer.status=='ready_for_verification' %>
     <td><span class="label label-info"> ready for verification </span></td>  
    <% end %>
<% if customer.status=='awaiting_to_get_verified' %>
     <td><span class="label label-warning"> in progress </span></td>  
    <% end %>
<% if customer.status=='verified' %>
     <td><span class="label label-success"> verified </span></td>  
    <% end %>

<% @verifier  = CustomerVerification.find_all_by_customer_id(customer) %>
<% @verifier.each do |v| %>
<% if v.tab.name %>
    <td><%= v.tab.name %></td>
<% else %>
    <td> jodv</td>
<% end %><% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br />



app/views/businesses/new.html.erb
<h1>New business</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<style>
 #servey_data{float:left; width:800px;border-right:2px solid black;}
 #servey_document{width:350px;float:right}
</style>

<%- model_class = Business -%>
<h2> Customer Detail</h2>

<div class="page-header">
  <%= link_to 'Main Detail',
              customer_path(@business.customer), :class => 'label'  %>

  <%= link_to t('.back', :default => t("helpers.links.back")),
              customers_path, :class => 'label'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_business_path(@business, :customer_id =>@business.customer), :class => 'label'  %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              business_path(@business),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'label label-important' %>
<% if @business.work_servey && @business.work_servey.name_and_employee_confirm %>
 <b style="background:red"><%= link_to "print this form", print_business_form_business_path(:business_id => @business ), :class => "label label-info" %></b>
<% end %>

<div id ="stamp" style="float:right">
<% if @business.status=='verified'%>
 <%= image_tag('verified-stamp.png', :size => "150x150") %>
<% end %>
</div>

<% if @business.status=="awaiting_to_get_verified" && current_user.role=="super_user" %>
  <p style="margin-right:50px;float:right">
    <%= link_to "Accept", accept_business_path(@business, :business_id=>@business), :class=>"label label-success" %> |
    <%= link_to "Re Assign", re_indicated_business_path(@business, :business_id=>@business), :class=>"label label-info" %>
  </p>
<% end %>
<br><br>

<h3 class ="label label-info">
 <%= "scorpeo-#{Date.today}-#{@business.application_ref_no}" %> | <%= @business.agency_name %>
</h3>
  <h4 style="color:blue"><%= @business.applicant_name %></h4>
  <b style="color:blue"><%= @business.department.name if @business.department %></b>
<% if @business.status=="submitted" %>
 <h6><%= link_to 'reasign to another tab', edit_business_verification_path(@business.business_verification, :id => @business.business_verification) %></h6>
<% end %>

<h5>
  <%= @business.address %> <br>
  <%= @business.country_name %> |
  <%= @business.country_state %> |
  <%= @business.country_city %> |
  <%= @business.pincode.name %>
  <%= @business.landmark %> <br>
</h5>

<% if @business.status=="ready_for_verification" %>
 <% if user_signed_in?&&current_user.role=="super_user" %>
   <%= form_for :business_verification_business_path, :url => business_verification_business_path(:business_id=>@business.id), :method=>:post do |f| %>
<%= select_tag "business_verification[tab_id]", options_for_select(Tab.all.collect {|r|[r.name,r.id]}), {:class=>'tf help',:style=>"margin-top:15px;"} %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= f.submit "Send for verification", :class=>"btn btn-primary btn-small" %>
      <% end %>
<% end %>
<% else %>

<% if @business.status=="submitted" %>
<br>
    <% if @business.status=='submitted' %>
     <span class="label label-warning">Submitted to Tab User </span><br>

<small>
 The customer has been send for verification. <br>
 Tab Name:
 <%= link_to @business.business_verification.tab.name, tab_path(@business.business_verification.tab) %></small>

    <% end %>
<% else %>
    <% if @business.status=='verified' %>
     <td><span class="label label-success">Verified </span></td></tr>
    <% end %>
    <% if @business.status=='verified_with_changes' %>
     <td><span class="label label-info">Verified with Changes </span></td></tr>
    <% end %>
<% end %>
<% end %>
</div>



<% if @business.business_documents.present? %>
<div id="servey_document">
<h4> Submitted Documents </h4><br>
<% @business.business_documents.each do |d| %>
	<% if d.photo? %>
	 <%= link_to image_tag(d.photo.url(:thumb)), d.photo.url(:large) %>
	<% else %>
   <%= image_tag("url.png", :size => "100x100") %>
	<% end %>
<% end %>
</div>
<% end %>


<% if @business.work_servey %>
<% if @business.work_servey.name_and_employee_confirm %>
<h4> Customer's Servey Detail | <%= link_to "Edit servey", edit_work_servey_path(@business.work_servey, :business_id=> @business, :tab_id=>@business.work_servey.tab_id) %></h4><br>

<div id="servey_data">
<table class="table table-bordered table-striped table-condensed" style="width:700px;">
  <tr><td><strong><%= model_class.human_attribute_name(:Designation) %>:</strong>
  <td><%= @business.work_servey.applicant_designation %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:date_of_visit) %>:</strong>
  <td><%= @business.work_servey.date_of_visit %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:time_of_visit) %>:</strong>
  <td><%= @business.work_servey.time_of_visit.strftime('%I:%M %P') %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:person_contacted) %>:</strong>
  <td><%= @business.work_servey.person_met %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:designation_of_person_met) %>:</strong>
  <td><%= @business.work_servey.designation_of_person_met %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:contact_number) %>:</strong>
  <td><%= @business.work_servey.telephone_number %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:extension_number) %>:</strong>
  <td><%= @business.work_servey.ext_number %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:mobile_number) %>:</strong>
  <td><%= @business.work_servey.mobile_number %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:no_of_years_in_present_employeement) %>:</strong>
  <td><%= @business.work_servey.number_of_years_in_present_employment %> Years<br>

  <tr><td><strong><%= model_class.human_attribute_name(:visiting_card_obtained) %>:</strong>
  <td><% if @business.work_servey.visiting_card_obtained="true" %>
   Yes <% else %> No <% end %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:name_of_the_company) %>:</strong>
  <td><%= @business.work_servey.name_of_the_company %></td>

<% if !@business.work_servey.company_name_new.blank? %>
  <p style="background:pink"><tr><td><strong><%= model_class.human_attribute_name(:Company_name_new) %>:</strong>
  <td><%= @business.work_servey.company_name_new %></td>
<% end %>

  <tr><td><strong><%= model_class.human_attribute_name(:type_of_business) %>:</strong>
  <td><%= @business.work_servey.type_of_business %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:nature_of_business) %>:</strong>
  <td><%= @business.work_servey.nature_of_business %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:nob_in_detail) %>:</strong>
  <td><%= @business.work_servey.nob_in_detail %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:office_ownership) %>:</strong>
  <td><%= @business.work_servey.office_ownership %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:no_of_employees) %>:</strong>
  <td><%= @business.work_servey.no_of_employees %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:no_of_branches) %>:</strong>
  <td><%= @business.work_servey.no_of_branches %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:average_monthly_turn_over) %>:</strong>
  <td><%= @business.work_servey.average_monthly_turn_over %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:no_of_customer_per_date) %>:</strong>
  <td><%= @business.work_servey.no_of_customer_per_date %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:type_of_job) %>:</strong>
  <td><%= @business.work_servey.type_of_job %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:customer_beaviour) %>:</strong>
  <td><%= @business.work_servey.job_transferable %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:salary_drawn) %>:</strong>
  <td><%= @business.work_servey.salary_drawn %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:Status) %>:</strong>
  <td><%= @business.work_servey.refer_to_bank %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:board_seen) %>:</strong>
  <td><%= @business.work_servey.board_seen %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:name_verified_from) %>:</strong>
  <td><%= @business.work_servey.name_verified_from %></td>

  <tr><td><strong><%= model_class.human_attribute_name(:verifier_remark) %>:</strong>
  <td><%= @business.work_servey.verifier_remark %></td>
</table>
</div>
<% end %>
<% end %>