config/routes.rb
EVerification::Application.routes.draw do
  [404,500].each do |page|
    get page, :to => "errors#show", code: page
  end

  # unless Rails.application.config.consider_all_requests_local
  #   match '*not_found', to: 'errors#error_404'
  # end

  root :to => 'dashboards#index'
  get "help_topics/" => 'help_topics#index', :as => :help_topics

  get "help_topics/how-to-make-applicant" => 'help_topics#make_customer', :as => :make_customer
  get "help_topics/how-to-make-co-applicant" => 'help_topics#make_co_applicant', :as => :make_co_applicant
  get 'pending_customers' => "reports#pending", :as => :pending_customers
  get 'completed_customers' => "reports#completed", :as => :completed_customers
  get 'progress_customers' => "reports#progress", :as => :progress_customers
	get 'get_branch_code' => "branches#get_branch_code"
	get 'get_area_name' => "branches#get_area_name"
	get 'get_area' => "branches#get_area"
  resources :branches
  resources :reports do
   get :generated_report
   get :generate_report
  end
  resources :co_applicant_serveys
  get "customers/download_ready_customers"
  get "customers/download_ready_co_applicants"
  get "customers/download_ready_customers_business"
  get "customers/download_ready_co_applicants_business"

  get "customers/completed_customers_today"
  get "customers/in_progress_today"
  get "customers/old_pending_customers"
  get "customers/daily_customers"
  get "customers/assigned_data_today"
  get "customers/daily_pending_customers"
  get "customers/daily_completed_customers"
  get "customers/daily_progress_customers"
  get "reports/show"
  get 'customers/reset'
  get "co_applicant_businesses/index"
  get "reports/to_excel" => "reports#to_excel", :as => :excel
  get "customers/search_results" => "customers#customer_search", :as => :search
  get "dashboards/index"
  get "headshot_demo/index"
  get "customers/cust_residential"
  get "customers/cust_business"
  get "customers/cust_pending"
  get "customers/cust_in_progress"
  get "customers/cust_ready"
  get "customers/cust_completed"
  get "customers/customer_search_results" => "customers#search", :as => :customer_search
  post "headshot/capture" => 'headshot#capture', :as => :headshot_capture

  #resources :searches
  resources :work_serveys
  resources :webcam_pictures
  resources :customers
  resources :tabs do
   get :tab_status
  end
  resources :profiles
  resources :pincodes
  resources :customer_documents

  resources :co_applicant_businesses do
   member do
     post :business_verification
     get :business_verification
     post :accept
     get :accept
     get :print_co_applicant_business
     post :re_indicated
     get :re_indicated
   end
     collection do
       post :assign_all
     end
  end

  resources :co_applicants do
    member do
     post :co_applicant_verification
     get :co_applicant_verification
     post :accept
     get :accept
     get :print_co_applicant
     post :re_indicated
     get :re_indicated
    end
     collection do
       post :assign_all
     end
  end
  resources :co_applicant_work_details
  resources :customer_verifications
  resources :business_verifications
  resources :co_applicant_verifications
  resources :client_verifications
  resources :serveys

  resources :customers do
    member do
     post :customer_verification
     get :customer_verification
     get :print_customer
     post :customer_work_servey_verification
     get :customer_work_servey_verification
     post :accept
     get :accept
     post :re_indicated
     get :re_indicated
    end
     collection do
       post :assign_all
     end
  end
  resources :businesses do
   member do
     post :business_verification
     get :business_verification
     post :accept
     get :print_business_form
     get :accept
     post :re_indicated
     get :re_indicated
   end
     collection do
       post :assign_all
     end
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :registrations => "registrations" } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
   include ApplicationHelper
   before_filter :authenticate_user!
   layout 'print_layout', :only => :print_customer
   load_and_authorize_resource

  def index
    @business = Business.without_status('ready_for_verification')
    @co_applicants = CoApplicant.without_status('ready_for_verification')
    @co_app_business = CoApplicantBusiness.without_status('ready_for_verification')
    @customers = Customer.without_status('ready_for_verification')
    filename = "customers.xls"
    @all_custome = (@business + @co_applicants + @co_app_business + @customers).sort_by {|a| a.created_at}.reverse
    #@all_customer = @all_customer.page(params[:page]).per(5)
    respond_to do |format|
      format.html do # index.html.erb
    		unless @all_custome.kind_of?(Array)
     			@all_customer = @all_custome.page(params[:page]).per(25)
		    else
			    @all_customer = Kaminari.paginate_array(@all_custome).page(params[:page]).per(25)
		    end
      format.json { render json: @all_customer }
      #format.xls { headers["Content-Disposition"] = "attachment; filename=\"#{filename}\"" }
      format.xls do
      render :xls => @all_custome,
             :columns => [ :application_status, :applicant_name, :address, :status ],
             :headers => %w[ Application_Status Applicant_Name Address Status ]
        end
      end
    end
  end

  def download_ready_customers
    @ready_customers = Customer.where('no_verifcation =? and status =?', false, 'ready_for_verification')
    respond_to do |format|
      format.html
      format.xls { send_data @ready_customers.to_csv(col_sep: "\t") }
    end
  end

    def download_ready_co_applicants
    @ready_customers = CoApplicant.where('status =?', 'ready_for_verification')
    respond_to do |format|
      format.html
      format.xls { send_data @ready_customers.to_csv(col_sep: "\t") }
    end
  end

  def download_ready_customers_business
    @ready_customers = Business.where('status =?', 'ready_for_verification')
    respond_to do |format|
      format.html
      format.xls { send_data @ready_customers.to_csv(col_sep: "\t") }
    end
  end


  def download_ready_co_applicants_business
    @ready_customers = CoApplicantBusiness.where('status =?', 'ready_for_verification')
    respond_to do |format|
      format.html
      format.xls { send_data @ready_customers.to_csv(col_sep: "\t") }
    end
  end


 def reset
  @customer = Customer.find(params[:customer_id])
  @customer.reset!
  customer_verification_id = CustomerVerification.find_by_customer_id(@customer.id)
  customer_verification_id.destroy
  redirect_to customer_path(@customer, :notice => "Succesfully restored")
 end

 def assign_all
    params[:customer_verification][:customer_ids].each do |t|
     params_customer = {}
     params_customer['customer_id'] = t
     @t = CustomerVerification.create(params_customer)
     @t.tab_id = params[:tab_id].to_i
     if @t.save
        @t.customer.submit!
     end
    end
     redirect_to customers_cust_ready_path, notice: "successful."
 end

 def old_pending_customers
 end

  def completed_customers_today
    @customers = Customer.where('DATE(created_at) = ? and status = ?', Date.today, 'verified')
    @business = Business.where('DATE(created_at) = ? and status = ?', Date.today, 'verified')
    @co_applicants = CoApplicant.where('DATE(created_at) = ? and status = ?', Date.today, 'verified')
    @co_applicant_business = CoApplicantBusiness.where('DATE(created_at) = ? and status = ?', Date.today, 'verified')
    @all_customers_today = @customers + @co_applicants + @co_applicant_business + @business
  end


  def in_progress_today
    @customers = Customer.where('DATE(created_at) = ? and status = ?', Date.today, 'awaiting_to_get_verified')
    @business = Business.where('DATE(created_at) = ? and status = ?', Date.today, 'awaiting_to_get_verified')
    @co_applicants = CoApplicant.where('DATE(created_at) = ? and status = ?', Date.today, 'awaiting_to_get_verified')
    @co_applicant_business = CoApplicantBusiness.where('DATE(created_at) = ? and status = ?', Date.today, 'awaiting_to_get_verified')
    @all_customers_today = @customers + @co_applicants + @co_applicant_business + @business
  end

  def daily_customers
    @customers = Customer.where('DATE(created_at) = ?', Date.today)
    @business = Business.where('DATE(created_at) = ?', Date.today)
    @co_applicants = CoApplicant.where('DATE(created_at) = ?', Date.today)
    @co_applicant_business = CoApplicantBusiness.where('DATE(created_at) = ?', Date.today)
    @all_customers_today = @customers + @co_applicants + @co_applicant_business + @business
  end

  def assigned_data_today
    @customers = CustomerVerification.where('DATE(created_at) = ?', Date.today)
    @business = BusinessVerification.where('DATE(created_at) = ?', Date.today)
    @co_applicants = CoApplicantVerification.where('DATE(created_at) = ?', Date.today)
    @co_applicant_business = ClientVerification.where('DATE(created_at) = ?', Date.today)
    @all_customers_today = @customers + @co_applicants + @co_applicant_business + @business

  end

  def daily_pending_customers
    @customers = Customer.where('DATE(created_at) = ? and status = ?', Date.today, 'submitted')
    @co_applicants = CoApplicant.where('DATE(created_at) = ? and status = ?', Date.today, 'submitted')
    @business = Business.where('DATE(created_at) = ? and status = ?', Date.today, 'submitted')
    @co_applicant_business = CoApplicantBusiness.where('DATE(created_at) = ? and status = ?', Date.today, 'submitted')
    @all_customers_today = @customers + @co_applicants + @co_applicant_business + @business
  end

  def search
    @business = Business.all
    @co_applicants = CoApplicant.all
    @co_app_business = CoApplicantBusiness.all
    @customers = Customer.all
    @customer_search = (@business + @co_applicants + @co_app_business + @customers).find.(:applicant_name, 'iLIKE', "%#{search}%")
  end

  def customer_search
   @start_date = params[:start] || Date.today-5
   @end_date = params[:end] || Date.today
   @customer_results = Customer.where("created_at >= ? and created_at <= ?", @start_date, @end_date)
  end

  def cust_residential
   @all_customer = residential
  end

  def cust_business
   @all_customer_business = business
  end

  def cust_pending
   @cust_pending = pending_filter
  end

  def cust_in_progress
   @cust_in_progress = in_progress_filter
  end

  def cust_completed
   @cust_completed = completed_filter
  end

  def cust_ready
    #@cust_ready = inqueue_filter
    @cust_ready = Customer.where('status = ? and  no_verifcation = ? ', 'ready_for_verification', false)
    @business_ready = Business.where('status = ?', 'ready_for_verification')
    @co_applicant_ready = CoApplicant.where('status = ?', 'ready_for_verification')
    @co_applicant_business_ready = CoApplicantBusiness.where('status = ?', 'ready_for_verification')
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])
    @google_address = @customer
    @customer_verification = @customer.customer_verification
    @business = Business.new
    @co_applicant = CoApplicant.new
    @application_ref_no = @customer.application_ref_no

   #authorize! :show, @customer

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json

  def new
    @customer = Customer.new
    @work_servey = WorkServey.new
     if Customer.any?
       @new_no = Customer.last.application_ref_no.to_i
       @final_no = (@new_no+1)
     else
       @final_no = 1001
       @date = Time.now
       @current_date = @date.strftime("%B %d, %Y")
     end
  end


  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
    @final_no = @customer.application_ref_no
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        #pincode = Pincode.find(@customer.pincode_id)
        #group_id = pincode.pincode_group_id if pincode
        #tab_id = Tab.find_by_pincode_group_id(group_id) if group_id

        #verification = CustomerVerification.create(user_id: current_user.id, tab_id: tab_id.id, customer_id: @customer.id) if tab_id
        #verification.save! && verification.customer.submit!
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json

  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
     if @customer.update_attributes(params[:customer])
        #@customer.progress!
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def print_customer
    @print_customer = Customer.find(params[:customer_id])
  end

 def customer_verification
   @customer = Customer.find(params[:customer_id])
   @tab = Tab.find(:all)
   @verification = CustomerVerification.create(params[:customer_verification])
    @verification.user_id = current_user.id
    @verification.customer_id = @customer.id

     if @verification.save
        @verification.customer.submit!

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/_form.html.erb
<%= form_for @customer, :html => { :class => 'form-horizontal' } do |f| %>
<% if @customer.blank? %>
  <div class="control-group">
    <%= f.label :application_ref_no, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :application_ref_no, :class => 'text_field', :value=>@ref_no %>
    </div>
  </div>
<% else %>
  <div class="control-group">
    <%= f.label :application_ref_no, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :application_ref_no, :class => 'text_field', :value=> @final_no %>
    </div>
  </div>
<% end %>
  <div class="control-group">
    <%= f.label :agency_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :agency_name, :class => 'text_field', :value=>"Scorp Enterprises" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :fh_code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :fh_code, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :applicant_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :applicant_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :address, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :landmark, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :landmark, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :date_of_birth, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :d_o_b, :start_year => 1930 %>
    </div>
  </div>


<br>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/customers/_show.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%= @customer.applicant_name %></h1>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              customers_path, :class => 'label'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_path(@customer), :class => 'label' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_path(@customer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'label label-important' %>  
  <% if @customer.status=="awaiting_to_get_verified" %>
    <p style="margin-right:50px;float:right">
      <%= link_to "Accept", accept_customer_path(@customer, :customer_id=>@customer), :class=>"label label-success" %> | 
      <%= link_to "Re Assign", re_indicated_customer_path(@customer, :customer_id=>@customer), :class=>"label label-info" %>
    </p>
  <% end %>

<h4>

<% if @customer.status=="ready_for_verification" %>
 <% if admin_user_signed_in?&&current_admin_user.role=="admin" %>
   <%= form_for :customer_verification_customer_path, :url => customer_verification_customer_path(:customer_id=>@customer.id), :method=>:post do |f| %>
<%= select_tag "customer_verification[tab_id]", options_for_select(Tab.all.collect {|r|[r.name,r.id]}), {:prompt=> 'select',:class=>'tf help'} %>
      <%= f.hidden_field :customer_id, :value=> @customer.id %>
      <%= f.submit "Send for verification", :class=>"btn" %>
      <% end %>
<% end %>
<% else %>

<% if @customer.status=="submitted" %>
<br>
    <% if @customer.status=='submitted' %>
     <td><span class="label label-warning">Submitted to Tab User </span></td></tr><br>
<i style="font-size:10px;color:orange;">
 The customer has been send for verification. this is been assigned to 
 <%= link_to @customer.customer_verification.tab.name, tab_path(@customer.customer_verification.tab) %></i>

    <% end %>
<% else %>
    <% if @customer.status=='verified' %>
     <td><span class="label label-success">Verified </span></td></tr>
    <% end %>
    <% if @customer.state=='verified_with_changes' %>
     <td><span class="label label-info">Verified with Changes </span></td></tr>
    <% end %>
<% end %>
<% end %>
</td></tr></tr></table>



</h4>

</div>



<div class="span3" style ="width:400px;padding:20px;border-radius:5px;border:1px solid #000000;text-align:center">
<table class="table table-striped">
  <tr><td><strong><%= model_class.human_attribute_name(:application_ref_no) %>:</strong>
  <%= @customer.application_ref_no %></td></tr></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:agency_name) %>:</strong>
  <%= @customer.agency_name %></td></tr></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:fh_code) %>:</strong>
  <%= @customer.fh_code %></td></tr></tr>


  <tr><td><strong><%= model_class.human_attribute_name(:address) %>:</strong>
  <%= @customer.address %></td></tr></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:landmark) %>:</strong>
  <%= @customer.landmark %></td></tr></tr>




</table>
</div>


<div class="span3" style ="width:400px;padding:20px;border-radius:5px;border:1px solid #000000;text-align:center">
<p><%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@customer.latitude}%2C#{@customer.longitude}" %></p>
</div>

<% if @customer.servey %>
<% if @customer.servey.address_confirmed? %>
<div class="span5" style ="width:400px;padding:20px;border-radius:5px;border:1px solid #000000;text-align:center">
<table class="table table-bordered">

  <tr><td><strong><%= model_class.human_attribute_name(:address_confirmed) %>:</strong>
  <% if @customer.servey.address_confirmed? %> Yes <% end %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:name_and_stay_confirm) %>:</strong>
  <%= @customer.servey.name_and_stay_confirm %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:date_of_visit) %>:</strong>
  <%= @customer.servey.date_of_visit %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:time_of_visit) %>:</strong>
  <%= @customer.servey.time_of_visit %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:person_contacted) %>:</strong>
  <%= @customer.servey.person_contacted %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:relation_with_applicant) %>:</strong>
  <%= @customer.servey.relation_with_applicant %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:d_o_b) %>:</strong>
  <%= @customer.d_o_b %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:years_lived_at_current_address) %>:</strong>
  <%= @customer.servey.years_lived_at_current_address %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:residence_status) %>:</strong>
  <%= @customer.servey.residence_status %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:educational_qualification) %>:</strong>
  <%= @customer.servey.educational_qualification %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:marital_status) %>:</strong>
  <%= @customer.servey.marital_status %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:no_of_family_members) %>:</strong>
  <%= @customer.servey.no_of_family_members %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:working_member) %>:</strong>
  <%= @customer.servey.working_member %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:children) %>:</strong>
  <%= @customer.servey.children %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:spouse_working) %>:</strong>
  <%= @customer.servey.spouse_working %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:spouse_working_detail) %>:</strong>
  <%= @customer.servey.spouse_working_detail %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:name_plate_seen) %>:</strong>
  <%= @customer.servey.name_plate_seen %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:credit_card) %>:</strong>
  <%= @customer.servey.credit_card %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:card_no) %>:</strong>
  <%= @customer.servey.card_no %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:card_limit) %>:</strong>
  <%= @customer.servey.card_limit %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:issuing_bank) %>:</strong>
  <%= @customer.servey.issuing_bank %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:expiry_date) %>:</strong>
  <%= @customer.servey.expiry_date %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:customer_beaviour) %>:</strong>
  <%= @customer.servey.customer_beaviour %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:neighbour_ref) %>:</strong>
  <%= @customer.servey.neighbour_ref %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:name_varified_from) %>:</strong>
  <%= @customer.servey.name_varified_from %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:type_of_residence) %>:</strong>
  <%= @customer.servey.type_of_residence %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:locality_of_residence) %>:</strong>
  <%= @customer.servey.locality_of_residence %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:ease_of_location) %>:</strong>
  <%= @customer.servey.ease_of_location %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:construction_of_residence) %>:</strong>
  <%= @customer.servey.construction_of_residence %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:comments_of_exteriors) %>:</strong>
  <%= @customer.servey.comments_of_exteriors %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:carpet_area_in_sq_feet) %>:</strong>
  <%= @customer.servey.carpet_area_in_sq_feet %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:interior_condition) %>:</strong>
  <%= @customer.servey.interior_condition %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:asset_seen_at_residence) %>:</strong>
  <%= @customer.servey.asset_seen_at_residence %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:potrait_on_wall) %>:</strong>
  <%= @customer.servey.potrait_on_wall %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:applicant_residing_detail) %>:</strong>
  <%= @customer.servey.applicant_residing_detail %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:application_availibility_time) %>:</strong>
  <%= @customer.servey.application_availibility_time %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:no_of_family_member_in_the_house) %>:</strong>
  <%= @customer.servey.no_of_family_member_in_the_house %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:verifiers_remark) %>:</strong>
  <%= @customer.servey.verifiers_remark %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:accept_or_decline) %>:</strong>
  <%= @customer.servey.accept_or_decline %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:refer_to_bank) %>:</strong>
  <%= @customer.servey.refer_to_bank %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:slug) %>:</strong>
  <%= @customer.slug %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:latitude) %>:</strong>
  <%= @customer.latitude %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:longitude) %>:</strong>
  <%= @customer.longitude %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:gmaps) %>:</strong>
  <%= @customer.gmaps %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:state) %>:</strong>
  <%= @customer.state %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:pin) %>:</strong>
  <%= @customer.pin %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:country_state) %>:</strong>
  <%= @customer.country_state %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:country_city) %>:</strong>
  <%= @customer.country_city %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:country_name) %>:</strong>
  <%= @customer.country_name %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:status) %>:</strong>
  <%= @customer.status %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:degree_name) %>:</strong>
  <%= @customer.degree_name %></td></tr>

</table>
</div>
<% end %>
<% end %>




