config/routes.rb
EVerification::Application.routes.draw do
  [404,500].each do |page|
    get page, :to => "errors#show", code: page
  end

  # unless Rails.application.config.consider_all_requests_local
  #   match '*not_found', to: 'errors#error_404'
  # end

  root :to => 'dashboards#index'
  get "help_topics/" => 'help_topics#index', :as => :help_topics

  get "help_topics/how-to-make-applicant" => 'help_topics#make_customer', :as => :make_customer
  get "help_topics/how-to-make-co-applicant" => 'help_topics#make_co_applicant', :as => :make_co_applicant
  get 'pending_customers' => "reports#pending", :as => :pending_customers
  get 'completed_customers' => "reports#completed", :as => :completed_customers
  get 'progress_customers' => "reports#progress", :as => :progress_customers
	get 'get_branch_code' => "branches#get_branch_code"
	get 'get_area_name' => "branches#get_area_name"
	get 'get_area' => "branches#get_area"
  resources :branches
  resources :reports do
   get :generated_report
   get :generate_report
  end
  resources :co_applicant_serveys
  get "customers/download_ready_customers"
  get "customers/download_ready_co_applicants"
  get "customers/download_ready_customers_business"
  get "customers/download_ready_co_applicants_business"

  get "customers/completed_customers_today"
  get "customers/in_progress_today"
  get "customers/old_pending_customers"
  get "customers/daily_customers"
  get "customers/assigned_data_today"
  get "customers/daily_pending_customers"
  get "customers/daily_completed_customers"
  get "customers/daily_progress_customers"
  get "reports/show"
  get 'customers/reset'
  get "co_applicant_businesses/index"
  get "reports/to_excel" => "reports#to_excel", :as => :excel
  get "customers/search_results" => "customers#customer_search", :as => :search
  get "dashboards/index"
  get "headshot_demo/index"
  get "customers/cust_residential"
  get "customers/cust_business"
  get "customers/cust_pending"
  get "customers/cust_in_progress"
  get "customers/cust_ready"
  get "customers/cust_completed"
  get "customers/customer_search_results" => "customers#search", :as => :customer_search
  post "headshot/capture" => 'headshot#capture', :as => :headshot_capture

  #resources :searches
  resources :work_serveys
  resources :webcam_pictures
  resources :customers
  resources :tabs do
   get :tab_status
  end
  resources :profiles
  resources :pincodes
  resources :customer_documents

  resources :co_applicant_businesses do
   member do
     post :business_verification
     get :business_verification
     post :accept
     get :accept
     get :print_co_applicant_business
     post :re_indicated
     get :re_indicated
   end
     collection do
       post :assign_all
     end
  end

  resources :co_applicants do
    member do
     post :co_applicant_verification
     get :co_applicant_verification
     post :accept
     get :accept
     get :print_co_applicant
     post :re_indicated
     get :re_indicated
    end
     collection do
       post :assign_all
     end
  end
  resources :co_applicant_work_details
  resources :customer_verifications
  resources :business_verifications
  resources :co_applicant_verifications
  resources :client_verifications
  resources :serveys

  resources :customers do
    member do
     post :customer_verification
     get :customer_verification
     get :print_customer
     post :customer_work_servey_verification
     get :customer_work_servey_verification
     post :accept
     get :accept
     post :re_indicated
     get :re_indicated
    end
     collection do
       post :assign_all
     end
  end
  resources :businesses do
   member do
     post :business_verification
     get :business_verification
     post :accept
     get :print_business_form
     get :accept
     post :re_indicated
     get :re_indicated
   end
     collection do
       post :assign_all
     end
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :registrations => "registrations" } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

end

app/controllers/co_applicant_businesses_controller.rb
class CoApplicantBusinessesController < ApplicationController
   before_filter :authenticate_user!
   layout 'print_layout', :only => :print_co_applicant_business
   load_and_authorize_resource

 def create
  @co_applicant = CoApplicantBusiness.create(params[:co_applicant_business])
   if @co_applicant.save
    redirect_to customer_path(@co_applicant.customer), :notice => "'#{@co_applicant.applicant_name}'s business Details Added."
   else
    redirect_to @co_applicant.customer, :notice => "Something went wrong , please contact the administrator!."
 end
 end

 def assign_all
    params[:co_applicant_business_verification][:co_applicant_business_ids].each do |t|
     params_customer = {}
     params_customer['co_applicant_business_id'] = t
     @t = ClientVerification.create(params_customer)
     @t.tab_id = params[:tab_id].to_i
     if @t.save
        @t.co_applicant_business.submit!
     end
    end
     redirect_to customers_cust_ready_path, notice: "successful."
 end


 def edit
  @co_applicant = CoApplicant.find(params[:co_applicant_id])
  @co_applicant_work_detail = CoApplicantBusiness.find(params[:id])
  @application_ref_no = @co_applicant.application_ref_no
 end

  def update
    @co_applicant_business = CoApplicantBusiness.find(params[:id])

    respond_to do |format|
     if @co_applicant_business.update_attributes(params[:co_applicant_business])
        format.html { redirect_to @co_applicant_business, notice: 'successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @co_applicant_business.errors, status: :unprocessable_entity }
      end
    end
  end

 def show
  @co_applicant_business = CoApplicantBusiness.find(params[:id])
 end

  def destroy
    @co_applicant_business = CoApplicantBusiness.find(params[:id])
    @co_applicant_business.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end



 def business_verification
   @co_applicant = CoApplicantBusiness.find(params[:business_id])
   @tab = Tab.find(:all)
   @verification = ClientVerification.create(params[:client_verification])
    @verification.user_id = current_user.id
    @verification.co_applicant_business_id = @co_applicant.id
     if @verification.save
        @verification.co_applicant_business.submit!
        @user = User.find_by_role('super_user')
        #VerificationMailer.verification_confirmation(@user).deliver
        redirect_to @co_applicant, :notice =>"record has been send for verification"
    end
  end

  def accept
    @co_applicant_business = CoApplicantBusiness.find(params[:co_applicant_business_id])
    @co_applicant_business.accept!

    respond_to do |format|
       if @co_applicant_business.update_attributes(params[:co_applicant_business])
         format.html { redirect_to root_url, notice: 'Status was successfully updated.' }
         format.json { head :ok }
       else
         format.html { render action: "edit" }
         format.json { render json: @co_applicant_business.errors, status: :unprocessable_entity }
       end
     end
  end

  def re_indicated
   @co_applicant_business = CoApplicantBusiness.find(params[:co_applicant_business_id])
    @business.re_indicated!

    respond_to do |format|
       if @co_applicant_business.update_attributes(params[:co_applicant_business])
         format.html { redirect_to root_url, notice: 'Status was successfully updated.' }
         format.json { head :ok }
       else
         format.html { render action: "edit" }
         format.json { render json: @co_applicant_business.errors, status: :unprocessable_entity }
       end
     end
  end


 def print_co_applicant_business
  #@print_co_applicant_business = CoApplicantBusiness.find(params[:business_id])
 end

end

app/helpers/co_applicant_businesses_helper.rb
module CoApplicantBusinessesHelper
end

app/views/co_applicant_businesses/_form.html.erb
<script stype="javascript">
 function getArea(obj){
 $.ajax({url:'/get_area',
 dataType: 'script',
 type: 'get',
 data: {id: obj.value},
 success: function(data){

 }
 });}
</script>

<script stype="javascript">
 function getAreaname(obj){
 $.ajax({url:'/get_area_name',
 dataType: 'text',
 type: 'get',
 data: {id: obj.value},
 success: function(data){
  $("#co_applicant_business_area_name").val(data);
 }
 });}
</script>

<div id="business" style ="padding-left:40px">
<%= form_for(@co_applicant_work_detail) do |f| %>
  <% if @co_applicant_work_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@co_applicant_work_detail.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @co_applicant_work_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="row">
  <strong class="label label-info">
    <%= @application_ref_no %> | <%= @application_ref_no %> | <%= @co_applicant.applicant_name %>
</strong> <br>

  <div class="field_name">
   <%= f.check_box :document_required %>
   <i style ="padding-left:20px;color:green">Check this if photocopy of the customers document is required. else leave it as it is</i>
  </div>
    <%= f.hidden_field :customer_id, :value=> "#{@co_applicant.customer.id}" %>
    <%= f.hidden_field :agency_name, :value=>"Scorp Enterprises" %>
    <%= f.hidden_field :application_ref_no, :value=> "#{@application_ref_no}" %>
    <%= f.hidden_field :fh_code, :value=> "#{@application_ref_no}" %>
    <%= f.hidden_field :applicant_name, :value=> "#{@co_applicant.applicant_name}" %>
    <%= f.hidden_field :application_status, :value => "BUSINESS" %>
    <%= f.hidden_field :client_id, :value => "#{@co_applicant.client_id}" %>
    <%= f.hidden_field :branch_id, :value => "#{@co_applicant.branch_id}" %>
    <%= f.hidden_field :branch_code, :value => "#{@co_applicant.branch_code}" %>
  <br><br>

  <div class="field_name">
    <%= f.label :'Name OF The Company' %>
    <%= f.text_field :company_name %>
  </div><br><br><br>

  <div class="field_name">
    <%= f.label :landmark %>
    <%= f.text_field :landmark %>
  </div><br><br><br>

  <div class="field_name">
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>

  <div class="field_name">
    <%= f.label :country_name %>
    <%= f.text_field :country, :value => "INDIA" %>
  </div>
  <div class="field_name">
    <%= f.label :country_state %>
    <%= f.text_field :state %>
  </div>
  <div class="field_name">
    <%= f.label :country_city %>
    <%= f.collection_select :city_id, City.all, :id, :name, {}, {:class => 'text_field', :onchange => 'getArea(this)'} %>
  </div>
  <div class="field_name">
    <%= f.label :pincode_id %>
  <div id ="area_name"><%= f.collection_select :pincode_id, Pincode.all, :id, :name, {:prompt => true} ,{:class => 'text_field', :onchange => 'getAreaname(this)'} %></div>
  </div>
  <div class="field_name">
    <%= f.label :'Selected pincode', :class => 'control-label' %>
    <%= f.text_field :area_name, :class => 'text_field' %>
  </div>

</div>
  <div class="actions">
    <%= f.submit 'Submit..', :class => 'btn btn-primary btn-small' %>
  </div>
<% end %>
</div>

app/views/co_applicant_businesses/_header.html.erb
<%- model_class = CoApplicantBusiness -%>
<div class="page-header">

  <%= link_to t('.back', :default => t("helpers.links.back")),
              businesses_path, :class => 'label'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_co_applicant_business_path(@co_applicant_business, :customer_id => @co_applicant_business.customer.co_applicant), :class => 'label' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              co_applicant_business_path(@co_applicant_business),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'label label-important' %>
<% if @co_applicant_business.co_applicant_work_detail && @co_applicant_business.co_applicant_work_detail.name_and_employee_confirm %>
 <b style="background:red"><%= link_to "print this form", print_co_applicant_business_co_applicant_business_path(:business_id => @co_applicant_business ), :class => "label label-info" %></b>
<% end %>


  <% if @co_applicant_business.status=="awaiting_to_get_verified"&&current_user.role=="super_user" %>
    <p style="margin-right:50px;float:right">
      <%= link_to "Accept", accept_co_applicant_business_path(@co_applicant_business, :co_applicant_business_id=>@co_applicant_business), :class=>"label label-success" %> |
      <%= link_to "Re Assign", re_indicated_co_applicant_business_path(@co_applicant_business, :co_applicant_business_id=>@co_applicant_business), :class=>"label label-info" %>
    </p>
  <% end %>
<br><br>

<div id ="stamp" style="float:right">
<% if @co_applicant_business.status=='verified'%>
 <%= image_tag('verified-stamp.png', :size => "150x150") %>
<% end %>
</div>

<h3 class ="label label-info">
 <%= "scorpeo-#{Date.today}-#{@co_applicant_business.application_ref_no}" %> | <%= @co_applicant_business.agency_name %>
</h3>
  <h4 style="color:blue"><%= @co_applicant_business.applicant_name %></h4>
    	 <% if @co_applicant_business.status=="submitted" %>
		   <h6><%= link_to 'reasign to another tab', edit_client_verification_path(@co_applicant_business.client_verification, :id => @co_applicant_business.client_verification) %></h6>
     <% end %>

<h5>
  <%= @co_applicant_business.landmark %> <br>
  <%= @co_applicant_business.address %> <br>
  <%= @co_applicant_business.country %> |
  <%= @co_applicant_business.state %> |
  <%= @co_applicant_business.city %> |
  <%= @co_applicant_business.pincode.name if @co_applicant_business.pincode %>
</h5>

<% if @co_applicant_business.status=="ready_for_verification" %>
 <% if user_signed_in?&&current_user.role=="super_user" %>
   <%= form_for :business_verification_co_applicant_business_path, :url => business_verification_co_applicant_business_path(:business_id=>@co_applicant_business.id), :method=>:post do |f| %>
<%= select_tag "client_verification[tab_id]", options_for_select(Tab.all.collect {|r|[r.name,r.id]}), {:class=>'tf help',:style=>"margin-top:15px;"} %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= f.submit "Send for verification", :class=>"btn btn-primary btn-small" %>
      <% end %>
<% end %>
<% else %>

<% if @co_applicant_business.status=="submitted" %>
<br>
    <% if @co_applicant_business.status=='submitted' %>
     <span class="label label-warning">Submitted to Tab User </span><br>
<small>
 The customer has been send for verification. this is been assigned to
 <%= link_to @co_applicant_business.client_verification.tab.name, tab_path(@co_applicant_business.client_verification.tab) %></small>

    <% end %>
<% else %>
    <% if @co_applicant_business.status=='verified' %>
     <td><span class="label label-success">Verified </span>
    <% end %>
    <% if @co_applicant_business.status=='verified_with_changes' %>
     <span class="label label-info">Verified with Changes </span>
    <% end %>
<% end %>
<% end %>

</div>


<% if @co_applicant_business.co_applicant_business_documents.present? %>
<div id="servey_document">
<h4> Submitted Documents </h4><br>
<% @co_applicant_business.co_applicant_business_documents.each do |d| %>
 <%= image_tag d.photo.url(:thumb) %>
<% end %>
</div><br><br><br>
<% end %>

app/views/co_applicant_businesses/edit.html.erb
<%= render 'form' %>

app/views/co_applicant_businesses/new.html.erb
<%= render 'form' %>

app/views/co_applicant_businesses/show.html.erb
<style>
 #servey_data{float:left; width:800px;border-right:2px solid black;}
 #servey_document{width:350px;float:right; border:0px solid black;margin:80px -55px;}
</style>
<%- model_class = CoApplicantBusiness -%>
<%= render 'header' %>






<% if @co_applicant_business.co_applicant_work_detail %>
<h4> Customer's Servey Detail | <%= link_to "edit business servey", edit_co_applicant_work_detail_path(@co_applicant_business.co_applicant_work_detail, :co_applicant_business_id => @co_applicant_business.co_applicant_work_detail.co_applicant_business_id, :tab_id => @co_applicant_business.co_applicant_work_detail.tab_id) %></h4><br>
<div id="servey_data">
<table class="table table-bordered table-striped table-condensed" style="width:700px;">

  <tr><td><strong><%= model_class.human_attribute_name(:Designation) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.applicant_designation %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:date_of_visit) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.date_of_visit %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:time_of_visit) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.time_of_visit.strftime('%I:%M %P') %><rb><br>

  <tr><td><strong><%= model_class.human_attribute_name(:person_contacted) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.person_met %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:designation_of_person_met) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.designation_of_person_met %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:contact_number) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.telephone_number %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:extension_number) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.ext_number %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:mobile_number) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.mobile_number %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:no_of_years_in_present_employeement) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.number_of_years_in_present_employment %> Years</td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:visiting_card_obtained) %>:</strong>
  <% if @co_applicant_business.co_applicant_work_detail.visiting_card_obtained="true" %>
   Yes <% else %> No <% end %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:name_of_the_company) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.name_of_the_company %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:type_of_business) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.type_of_business %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:nature_of_business) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.nature_of_business %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:nob_in_detail) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.nob_in_detail %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:office_ownership) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.office_ownership %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:no_of_employees) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.no_of_employees %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:no_of_branches) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.no_of_branches %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:average_monthly_turn_over) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.average_monthly_turn_over %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:no_of_customer_per_date) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.no_of_customer_per_date %><br>

  <tr><td><strong><%= model_class.human_attribute_name(:type_of_job) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.type_of_job %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:customer_beaviour) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.job_transferable %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:salary_drawn) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.salary_drawn %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:board_seen) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.board_seen %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:name_verified_from) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.name_verified_from %></td></tr>

  <tr><td><strong><%= model_class.human_attribute_name(:verifier_remark) %>:</strong>
  <%= @co_applicant_business.co_applicant_work_detail.verifier_remark %></td></tr>

</div>
<% end %>