config/routes.rb
EVerification::Application.routes.draw do
  [404,500].each do |page|
    get page, :to => "errors#show", code: page
  end

  # unless Rails.application.config.consider_all_requests_local
  #   match '*not_found', to: 'errors#error_404'
  # end

  root :to => 'dashboards#index'
  get "help_topics/" => 'help_topics#index', :as => :help_topics

  get "help_topics/how-to-make-applicant" => 'help_topics#make_customer', :as => :make_customer
  get "help_topics/how-to-make-co-applicant" => 'help_topics#make_co_applicant', :as => :make_co_applicant
  get 'pending_customers' => "reports#pending", :as => :pending_customers
  get 'completed_customers' => "reports#completed", :as => :completed_customers
  get 'progress_customers' => "reports#progress", :as => :progress_customers
	get 'get_branch_code' => "branches#get_branch_code"
	get 'get_area_name' => "branches#get_area_name"
	get 'get_area' => "branches#get_area"
  resources :branches
  resources :reports do
   get :generated_report
   get :generate_report
  end
  resources :co_applicant_serveys
  get "customers/download_ready_customers"
  get "customers/download_ready_co_applicants"
  get "customers/download_ready_customers_business"
  get "customers/download_ready_co_applicants_business"

  get "customers/completed_customers_today"
  get "customers/in_progress_today"
  get "customers/old_pending_customers"
  get "customers/daily_customers"
  get "customers/assigned_data_today"
  get "customers/daily_pending_customers"
  get "customers/daily_completed_customers"
  get "customers/daily_progress_customers"
  get "reports/show"
  get 'customers/reset'
  get "co_applicant_businesses/index"
  get "reports/to_excel" => "reports#to_excel", :as => :excel
  get "customers/search_results" => "customers#customer_search", :as => :search
  get "dashboards/index"
  get "headshot_demo/index"
  get "customers/cust_residential"
  get "customers/cust_business"
  get "customers/cust_pending"
  get "customers/cust_in_progress"
  get "customers/cust_ready"
  get "customers/cust_completed"
  get "customers/customer_search_results" => "customers#search", :as => :customer_search
  post "headshot/capture" => 'headshot#capture', :as => :headshot_capture

  #resources :searches
  resources :work_serveys
  resources :webcam_pictures
  resources :customers
  resources :tabs do
   get :tab_status
  end
  resources :profiles
  resources :pincodes
  resources :customer_documents

  resources :co_applicant_businesses do
   member do
     post :business_verification
     get :business_verification
     post :accept
     get :accept
     get :print_co_applicant_business
     post :re_indicated
     get :re_indicated
   end
     collection do
       post :assign_all
     end
  end

  resources :co_applicants do
    member do
     post :co_applicant_verification
     get :co_applicant_verification
     post :accept
     get :accept
     get :print_co_applicant
     post :re_indicated
     get :re_indicated
    end
     collection do
       post :assign_all
     end
  end
  resources :co_applicant_work_details
  resources :customer_verifications
  resources :business_verifications
  resources :co_applicant_verifications
  resources :client_verifications
  resources :serveys

  resources :customers do
    member do
     post :customer_verification
     get :customer_verification
     get :print_customer
     post :customer_work_servey_verification
     get :customer_work_servey_verification
     post :accept
     get :accept
     post :re_indicated
     get :re_indicated
    end
     collection do
       post :assign_all
     end
  end
  resources :businesses do
   member do
     post :business_verification
     get :business_verification
     post :accept
     get :print_business_form
     get :accept
     post :re_indicated
     get :re_indicated
   end
     collection do
       post :assign_all
     end
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :registrations => "registrations" } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
include ApplicationHelper
include ReportsHelper
  def index
   @start_date = params[:start_date] || Date.today-5
   @end_date = params[:end_date] || Date.today
   @tab_id = params[:tab_id].to_i
   @status = params[:status]
   @application_status = params[:application_status]
#all true
  if @tab_id!=0 && @status!='All' && @application_status!='All' && params[:start_date] && params[:end_date]
      @customers = CustomerVerification.joins(:customer).where('customer_verifications.tab_id = ? and DATE(customer_verifications.created_at) >= ? and DATE(customer_verifications.created_at) <= ? and customers.status = ? and customers.application_status = ? ', @tab_id , @start_date, @end_date, @status, @application_status)
     @co_applicants = CoApplicantVerification.joins(:co_applicant).where('co_applicant_verifications.tab_id = ? and DATE(co_applicant_verifications.created_at) >= ? and DATE(co_applicant_verifications.created_at) <= ? and co_applicants.status = ? and co_applicants.application_status = ? ', @tab_id, @start_date, @end_date, @status, @application_status)
     @business = BusinessVerification.joins(:business).where('business_verifications.tab_id = ? and DATE(business_verifications.created_at) >= ? and DATE(business_verifications.created_at) <= ? and businesses.status = ? and businesses.application_status = ?', @tab_id, @start_date, @end_date, @status, @application_status)
     @work_detail = ClientVerification.joins(:co_applicant_business).where('client_verifications.tab_id = ? and DATE(client_verifications.created_at) >= ? and DATE(client_verifications.created_at) <= ? and co_applicant_businesses.status = ? and co_applicant_businesses.application_status = ? ', @tab_id, @start_date, @end_date, @status,@application_status)
      @total = (@customers + @co_applicants + @business + @work_detail).count

      @pending_customers = @customers.where('customers.status = ?', 'submitted').count
      @pending_co_applicants = @co_applicants.where('co_applicants.status = ?', 'submitted').count
      @pending_business = @business.where('businesses.status = ?', 'submitted').count
      @pending_work = @work_detail.where('co_applicant_businesses.status = ?', 'submitted').count
      @all_pending = @pending_customers +@pending_co_applicants + @pending_business+@pending_work

      @completed_customers = @customers.where('customers.status = ?', 'verified').count
      @completed_co_applicants = @co_applicants.where('co_applicants.status = ?', 'verified').count
      @completed_business = @business.where('businesses.status = ?', 'verified').count
      @completed_work = @work_detail.where('co_applicant_businesses.status = ?', 'verified').count
      @all_completed = @completed_customers +@completed_co_applicants + @completed_business + @completed_work

      @progress_customers = @customers.where('customers.status = ?', 'awaiting_to_get_verified').count
      @progress_co_applicants = @co_applicants.where('co_applicants.status = ?', 'awaiting_to_get_verified').count
      @progress_business = @business.where('businesses.status = ?', 'awaiting_to_get_verified').count
      @progress_work = @work_detail.where('co_applicant_businesses.status = ?', 'awaiting_to_get_verified').count
      @all_progress = @progress_customers +@progress_co_applicants + @progress_business + @progress_work

#status false
   elsif @tab_id!=0 && @application_status!='All' && params[:start_date] && params[:end_date]
      @customers = CustomerVerification.joins(:customer).where("customer_verifications.tab_id = ? and customer_verifications.created_at >= ? and customer_verifications.created_at <= ? and customers.application_status = ? ", @tab_id, @start_date, @end_date, @application_status)

     @co_applicants = CoApplicantVerification.joins(:co_applicant).where('co_applicant_verifications.tab_id = ? and co_applicant_verifications.created_at >= ? and co_applicant_verifications.created_at <= ? and co_applicants.application_status = ?', @tab_id, @start_date, @end_date, @application_status)

     @business = BusinessVerification.joins(:business).where('business_verifications.tab_id = ? and business_verifications.created_at >= ? and business_verifications.created_at <= ? and businesses.application_status = ? ', @tab_id, @start_date, @end_date, @application_status)

     @work_detail = ClientVerification.joins(:co_applicant_business).where('client_verifications.tab_id = ? and client_verifications.created_at >= ? and client_verifications.created_at <= ? and co_applicant_businesses.application_status = ?', @tab_id, @start_date, @end_date, @application_status)

      @total = (@customers + @co_applicants + @business + @work_detail).count

      @pending_customers = @customers.where('customers.status = ?', 'submitted').count
      @pending_co_applicants = @co_applicants.where('co_applicants.status = ?', 'submitted').count
      @pending_business = @business.where('businesses.status = ?', 'submitted').count
      @pending_work = @work_detail.where('co_applicant_businesses.status = ?', 'submitted').count
      @all_pending = @pending_customers +@pending_co_applicants + @pending_business+@pending_work

      @completed_customers = @customers.where('customers.status = ?', 'verified').count
      @completed_co_applicants = @co_applicants.where('co_applicants.status = ?', 'verified').count
      @completed_business = @business.where('businesses.status = ?', 'verified').count
      @completed_work = @work_detail.where('co_applicant_businesses.status = ?', 'verified').count
      @all_completed = @completed_customers +@completed_co_applicants + @completed_business + @completed_work

      @progress_customers = @customers.where('customers.status = ?', 'awaiting_to_get_verified').count
      @progress_co_applicants = @co_applicants.where('co_applicants.status = ?', 'awaiting_to_get_verified').count
      @progress_business = @business.where('businesses.status = ?', 'awaiting_to_get_verified').count
      @progress_work = @work_detail.where('co_applicant_businesses.status = ?', 'awaiting_to_get_verified').count
      @all_progress = @progress_customers +@progress_co_applicants + @progress_business + @progress_work

#tab false
   elsif @status!='All' && @application_status!='All' && params[:start_date] && params[:end_date]
      @customers = CustomerVerification.joins(:customer).where("customers.status = ? and customer_verifications.created_at >= ? and customer_verifications.created_at <= ? and customers.application_status = ? ", @status, @start_date, @end_date, @application_status)

     @co_applicants = CoApplicantVerification.joins(:co_applicant).where('co_applicants.status = ? and co_applicant_verifications.created_at >= ? and co_applicant_verifications.created_at <= ? and co_applicants.application_status = ?', @status, @start_date, @end_date, @application_status)

     @business = BusinessVerification.joins(:business).where('businesses.status = ? and business_verifications.created_at >= ? and business_verifications.created_at <= ? and businesses.application_status = ? ', @status, @start_date, @end_date, @application_status)

     @work_detail = ClientVerification.joins(:co_applicant_business).where('co_applicant_businesses.status = ? and client_verifications.created_at >= ? and client_verifications.created_at <= ? and co_applicant_businesses.application_status = ?', @status, @start_date, @end_date, @application_status)

      @total = (@customers + @co_applicants + @business + @work_detail).count

      @pending_customers = @customers.where('customers.status = ?', 'submitted').count
      @pending_co_applicants = @co_applicants.where('co_applicants.status = ?', 'submitted').count
      @pending_business = @business.where('businesses.status = ?', 'submitted').count
      @pending_work = @work_detail.where('co_applicant_businesses.status = ?', 'submitted').count
      @all_pending = @pending_customers +@pending_co_applicants + @pending_business+@pending_work

      @completed_customers = @customers.where('customers.status = ?', 'verified').count
      @completed_co_applicants = @co_applicants.where('co_applicants.status = ?', 'verified').count
      @completed_business = @business.where('businesses.status = ?', 'verified').count
      @completed_work = @work_detail.where('co_applicant_businesses.status = ?', 'verified').count
      @all_completed = @completed_customers +@completed_co_applicants + @completed_business + @completed_work

      @progress_customers = @customers.where('customers.status = ?', 'awaiting_to_get_verified').count
      @progress_co_applicants = @co_applicants.where('co_applicants.status = ?', 'awaiting_to_get_verified').count
      @progress_business = @business.where('businesses.status = ?', 'awaiting_to_get_verified').count
      @progress_work = @work_detail.where('co_applicant_businesses.status = ?', 'awaiting_to_get_verified').count
      @all_progress = @progress_customers +@progress_co_applicants + @progress_business + @progress_work

#tab and status false
   elsif @application_status!='All' && params[:start_date] && params[:end_date]
      @customers = CustomerVerification.joins(:customer).where("customer_verifications.created_at >= ? and customer_verifications.created_at <= ? and customers.application_status = ? ", @start_date, @end_date, @application_status)

     @co_applicants = CoApplicantVerification.joins(:co_applicant).where('co_applicant_verifications.created_at >= ? and co_applicant_verifications.created_at <= ? and co_applicants.application_status = ?', @start_date, @end_date, @application_status)

     @business = BusinessVerification.joins(:business).where('business_verifications.created_at >= ? and business_verifications.created_at <= ? and businesses.application_status = ? ', @start_date, @end_date, @application_status)


app/helpers/reports_helper.rb
module ReportsHelper
 def all_reports(start_date, end_date)
   customers = Customer.where("created_at >= ? and created_at <= ?", start_date, end_date)
   co_applicants = CoApplicant.where("created_at >= ? and created_at <= ?", start_date, end_date)
   business = Business.where("created_at >= ? and created_at <= ?", start_date, end_date)
   co_app_business = CoApplicantBusiness.where("created_at >= ? and created_at <= ?", start_date, end_date)
   reports = customers+co_applicants+business+co_app_business
 end
end

app/views/reports/completed.html.erb
<style>
#hero-unit{font-size:11px;width:2000px;}
</style>

<h4>
 <%= link_to "Export to excel", completed_customers_path(:tab_id => params[:tab_id].to_i, :status => params[:status],
     :application_status=> params[:application_status],:start_date => params[:start_date], :end_date => params[:end_date],
      format: :xls) %>
</h4><hr>

<% if @completed_customers.present? || @completed_co_applicants.present? %>
<table class="table table-condensed table-bordered table-striped" style="width:1800px;">
 <thead>
  <tr>
    <th>Status </th>
    <th>Tab Name  </th>
    <th>Applicant name</th>
    <th>Applicant Address</th>
    <th>VisitDate</th>
    <th width="60px">VisitTime</th>
    <th>Person Contacted</th>
    <th>Relationship</th>
    <th>BirthDate</th>
    <th>Years at Current Address</th>
    <th>Residence Status</th>
    <th>Qualification</th>
    <th>Family Members</th>
    <th>Status</th>
    <th>Verifier Remark</th>
  </tr>
 </thead>
 <tbody>
 <% @completed_customers.each do |customer| %>
  <tr>
   <% if customer.customer.application_status == 'RESIDENTIAL' %>
   <td><b><%= customer.customer.application_status %></b></td>
   <% else %>
   <td><b><%= customer.customer.application_status %></b></td>
   <% end %>
   <td><%= customer.tab.name %></td>
   <td><%= customer.customer.applicant_name %></td>
   <td><%= customer.customer.address %></td>
   <td><%= customer.customer.servey.date_of_visit %></td>
   <td><%= customer.customer.servey.time_of_visit.strftime("%H:%M %p") %></td>
   <td><%= customer.customer.servey.person_contacted %></td>
   <td><%= customer.customer.servey.relation_with_applicant %></td>
   <td><%= customer.customer.servey.date_of_birth %></td>
   <td><%= customer.customer.servey.years_lived_at_current_address %> Yrs</td>
   <td><%= customer.customer.servey.residence_status %></td>
   <td><%= customer.customer.servey.educational_qualification %></td>
   <td><%= customer.customer.servey.no_of_family_members %></td>

   <% if customer.customer.status=='submitted' %>
   <td><span class="label label-info"> Pending </span></td>
   <% end %>
   <% if customer.customer.status=='ready_for_verification' %>
   <td><span class="label label-info"> ready for verification </span></td>
   <% end %>

   <% if customer.customer.status=='awaiting_to_get_verified' %>
   <td><span class="label label-warning"> in progress </span></td>
   <% end %>
   <% if customer.customer.status=='verified' %>
   <td><span class="label label-success"> verified </span></td>
   <% end %>
   <td>
     <%= customer.customer.servey.verifiers_remark %> ;
     <%= customer.customer.servey.date_of_visit %> ;
     <%= customer.customer.servey.time_of_visit.strftime("%H:%M %p") %>;
     <%= customer.customer.servey.person_contacted %>;
     <%= customer.customer.servey.relation_with_applicant %>;
     <%= customer.customer.servey.date_of_birth %>;
     <%= customer.customer.servey.years_lived_at_current_address %> Yrs;
     <%= customer.customer.servey.residence_status %>;
     <%= customer.customer.servey.educational_qualification %>
   </td>
 	 </tr>
	 <% end %>
	 </tbody>
<!--------------- Co Applicant ---------------------------------------------------------------------->

 <% @completed_co_applicants.each do |customer| %>

  <tr>
   <% if customer.co_applicant.application_status == 'RESIDENTIAL' %>
   <td><b><%= customer.co_applicant.application_status %></b></td>
   <% else %>
   <td><b><%= customer.co_applicant.application_status %></b></td>
   <% end %>
   <td><%= customer.tab.name %></td>
   <td><%= customer.co_applicant.applicant_name %></td>
   <td><%= customer.co_applicant.address %></td>
   <td><%= customer.co_applicant.co_applicant_servey.date_of_visit %></td>
   <td><%= customer.co_applicant.co_applicant_servey.time_of_visit.strftime("%H:%M %p") %></td>
   <td><%= customer.co_applicant.co_applicant_servey.person_contacted %></td>
   <td><%= customer.co_applicant.co_applicant_servey.relation_with_applicant %></td>
   <td><%= customer.co_applicant.co_applicant_servey.date_of_birth %></td>
   <td><%= customer.co_applicant.co_applicant_servey.years_lived_at_current_address %> Yrs</td>
   <td><%= customer.co_applicant.co_applicant_servey.residence_status %></td>
   <td><%= customer.co_applicant.co_applicant_servey.educational_qualification %></td>
   <td><%= customer.co_applicant.co_applicant_servey.no_of_family_members %></td>

   <% if customer.co_applicant.status=='submitted' %>
   <td><span class="label label-info"> Pending </span></td>
   <% end %>
   <% if customer.co_applicant.status=='ready_for_verification' %>
   <td><span class="label label-info"> ready for verification </span></td>
   <% end %>

   <% if customer.co_applicant.status=='awaiting_to_get_verified' %>
   <td><span class="label label-warning"> in progress </span></td>
   <% end %>
   <% if customer.co_applicant.status=='verified' %>
   <td><span class="label label-success"> verified </span></td>
   <% end %>
   <td>
     <%= customer.co_applicant.co_applicant_servey.verifiers_remark %> ;
     <%= customer.co_applicant.co_applicant_servey.date_of_visit %> ;
     <%= customer.co_applicant.co_applicant_servey.time_of_visit.strftime("%H:%M %p") %>;
     <%= customer.co_applicant.co_applicant_servey.person_contacted %>;
     <%= customer.co_applicant.co_applicant_servey.relation_with_applicant %>;
     <%= customer.co_applicant.co_applicant_servey.date_of_birth %>;
     <%= customer.co_applicant.co_applicant_servey.years_lived_at_current_address %> Yrs;
     <%= customer.co_applicant.co_applicant_servey.residence_status %>;
     <%= customer.co_applicant.co_applicant_servey.educational_qualification %>
   </td>
 	 </tr>
	 </tbody>
 </table>
<% end %>
<% end %>

<% if @completed_business.present? || @completed_work.present? %>
<table class="table table-condensed table-bordered table-striped" style="width:1800px;">
 <thead>
  <tr>
    <th>Status </th>
    <th>Applicant name</th>
    <th>Applicant Address</th>
    <th>VisitDate</th>
    <th width="60px">VisitTime</th>
    <th>Applicant Designation</th>
    <th>Person Met</th>
    <th>Designation of person met</th>
    <th>Telephone Number</th>
    <th>Mobile Number</th>
    <th>Years in Present Employement/Business</th>
    <th>Name Of Company/Business</th>
    <th>Status</th>
    <th>Verifier Remark</th>
  </tr>
 </thead>
 <tbody>



<!--------------- business---------------------------------------------------------------------->
 <% @completed_business.each do |b| %>

  <tr>
   <% if b.business.application_status == 'RESIDENTIAL' %>
   <td><b><%= b.business.application_status %></b></td>
   <% else %>
   <td><b><%= b.business.application_status %></b></td>
   <% end %>
   <td><%= b.business.applicant_name %></td>
   <td><%= b.business.address %></td>
   <td><%= b.business.work_servey.date_of_visit %></td>
   <td><%= b.business.work_servey.time_of_visit.strftime("%H:%M %p") %></td>
   <td><%= b.business.work_servey.applicant_designation %></td>
   <td><%= b.business.work_servey.person_met %></td>
   <td><%= b.business.work_servey.designation_of_person_met %></td>
   <td><%= b.business.work_servey.telephone_number %></td>
   <td><%= b.business.work_servey.mobile_number %></td>
   <td><%= b.business.work_servey.number_of_years_in_present_employment %> Yrs</td>
   <td><%= b.business.work_servey.name_of_the_company %></td>
   <td><%= b.business.work_servey.verifier_remark %></td>
   <td>
     <%= b.business.work_servey.verifier_remark %> ;
     <%= b.business.work_servey.date_of_visit %> ;
     <%= b.business.work_servey.time_of_visit.strftime("%H:%M %p") %>;
     <%= b.business.work_servey.applicant_designation %>;
     <%= b.business.work_servey.person_met %>;
     <%= b.business.work_servey.designation_of_person_met %>;
     <%= b.business.work_servey.telephone_number %>;
     <%= b.business.work_servey.number_of_years_in_present_employment %> Yrs.
   </td>
   <% if b.business.status=='submitted' %>
   <td><span class="label label-info"> Pending </span></td>
   <% end %>
   <% if b.business.status=='ready_for_verification' %>
   <td><span class="label label-info"> ready for verification </span></td>
   <% end %>

   <% if b.business.status=='awaiting_to_get_verified' %>
   <td><span class="label label-warning"> in progress </span></td>
   <% end %>
   <% if b.business.status=='verified' %>
   <td><span class="label label-success"> verified </span></td>
   <% end %>

 	 </tr>
	 <% end %>
	 </tbody>

<!--------------- Co Applicant Business ---------------------------------------------------------------------->
 <% @completed_work.each do |cb| %>

  <tr>
   <% if cb.co_applicant_business.application_status == 'RESIDENTIAL' %>
   <td><b><%= cb.co_applicant_business.application_status %></b></td>
   <% else %>
   <td><b><%= cb.co_applicant_business.application_status %></b></td>
   <% end %>
   <td><%= cb.co_applicant_business.applicant_name %></td>
   <td><%= cb.co_applicant_business.address %></td>
   <td><%= cb.co_applicant_business.co_applicant_work_detail.date_of_visit %></td>
   <td><%= cb.co_applicant_business.co_applicant_work_detail.time_of_visit.strftime("%H:%M %p") %></td>
   <td><%= cb.co_applicant_business.co_applicant_work_detail.applicant_designation %></td>
   <td><%= cb.co_applicant_business.co_applicant_work_detail.person_met %></td>
   <td><%= cb.co_applicant_business.co_applicant_work_detail.designation_of_person_met %></td>
   <td><%= cb.co_applicant_business.co_applicant_work_detail.telephone_number %></td>
   <td><%= cb.co_applicant_business.co_applicant_work_detail.mobile_number %></td>
   <td><%= cb.co_applicant_business.co_applicant_work_detail.number_of_years_in_present_employment %></td>
   <td><%= cb.co_applicant_business.co_applicant_work_detail.name_of_the_company %></td>
   <td><%= cb.co_applicant_business.co_applicant_work_detail.verifier_remark %></td>
   <% if cb.co_applicant_business.status=='submitted' %>
   <td><span class="label label-info"> Pending </span></td>
   <% end %>
   <% if cb.co_applicant_business.status=='ready_for_verification' %>
   <td><span class="label label-info"> ready for verification </span></td>
   <% end %>

   <% if cb.co_applicant_business.status=='awaiting_to_get_verified' %>
   <td><span class="label label-warning"> in progress </span></td>
   <% end %>
   <% if cb.co_applicant_business.status=='verified' %>
   <td><span class="label label-success"> verified </span></td>
   <% end %>
 	 </tr>
	 <% end %>
	 </tbody>
	 </table>
<% end %>

app/views/reports/index.html.erb
<style>
select {
    background-color: #FFFFFF;
    border: 1px solid #CCCCCC;
    width: 149px;
}
input[type="submit"] {
    font-size: 12px;
}


</style>


<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<%= javascript_include_tag "bootstrap-datepicker.js" %>

<script type="text/javascript">
jQuery(document).ready(function() {
    // binds form submission and fields to the validation engine
    // jQuery("form").validationEngine();
    var myDate = new Date("March 21, 1997");
     console.log('myDate');
    $('.datepicker').datepicker({
        changeMonth: true,
        changeYear: true,
        yearRange: '-14:-75',
        defaultDate: myDate
    });
  });
</script>

<%= form_for :reports_path, :method => :get do |f| %>
<div class ="row">
  <div class="field_name">
  <%= label_tag :'Select Tab' %>
  <%= select_tag :tab_id, options_for_select(Tab.all.map{ |c| [c.name, c.id] }), :prompt => "All Tabs" %>
  </div>
  <div class="field_name">
  <%= label_tag :'Select Status' %>
  <%= select_tag(:status, options_for_select([['All'], ['Pending', 'submitted'], ['progress', 'awaiting_to_get_verified'], ['Complete', 'verified']])) %>
  </div>

  <div class="field_name">
  <%= label_tag :'Application Type' %>
  <%= select_tag(:application_status, options_for_select([['All'], ['RESIDENTIAL', 'RESIDENTIAL'], ['BUSINESS', 'BUSINESS']])) %>
  </div>

  <div class="field_name">
  <%= label_tag :'Choose Start Date' %>
  <%= text_field_tag :start_date, '', :class=> "datepicker", :value => @start_date %>
  </div>
  <div class="field_name">
  <%= label_tag :'Choose End Date' %>
  <%= text_field_tag :end_date, '', :class => "datepicker", :value => @end_date %>
  </div><br><br><br><br>

<%= f.submit "Generate Report", :class =>"btn btn-info" %><hr>
</div>
<% end %>
<% if @customers.nil? %>
 <% else %>

 <h5>Customer Report from <%= params[:start_date] %> to <%= params[:end_date] %></h5><br><br>
<table class="table table-condensed table-striped table-bordered" style="width:400px;">

 <tr>
	 <td>Customer type </td>
	 <td><%= params[:application_status] %></td>
	</tr>

 <tr>
	 <td>Status </td>
	 <td><%= params[:status] %></td>
	</tr>

	<tr>
	 <% if params[:tab_id].present? %>
	 <% @name = Tab.find(params[:tab_id]) %>
	 <td>Tab name </td>
	 <td><%= @name.name %></td>
	</tr>

	 <% else %>
	<tr>
	 <td>Tab </td>
	 <td> All </td>
	</tr>

	 <% end %>

	<tr>


</table>




<table class="table table-condensed table-bordered table-striped">
 <tr>
  <td> Pending </td>
  <td> Completed </td>
  <td> In Progress </td>
  <td> Total </td>
 </tr>
 <tr>
   <td><%= link_to @all_pending, pending_customers_path(tab_id: params[:tab_id], status: params[:status], start_date: params[:start_date], end_date: params[:end_date], application_status: params[:application_status]) %></td>
   <td><%= link_to @all_completed, completed_customers_path(tab_id: params[:tab_id], status: params[:status], start_date: params[:start_date], end_date: params[:end_date], application_status: params[:application_status]) %></td>
   <td><%= link_to @all_progress, progress_customers_path(tab_id: params[:tab_id], status: params[:status], start_date: params[:start_date], end_date: params[:end_date], application_status: params[:application_status])  %></td>
   <td><%= link_to @total %></td>
</table>

</div>

<% end %>

app/views/reports/index.xls.erb
<%= render "index" %>

app/views/reports/show.html.erb
test